# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8266e67c3947116f13624005ec07a6d0dc3ff4583957f273b9c98f8d3a0327039aa3e982e0e2367401fca6e5dbe734848a658f783a9feea0211b39b6101930be

test:
  secret_key_base: 8bf805b323f89a051237e8014fdb7b05cd3cb4c51cb52750c698ca5529e8f6b5fe24b574b631195cad672730b0641a7d52683ea98b76473d7057cbdfb6681d00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
